// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/money_movement.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerWalletUserId string                 `protobuf:"bytes,1,opt,name=customer_wallet_user_id,json=customerWalletUserId,proto3" json:"customer_wallet_user_id,omitempty"`
	MerchantWalletUserId string                 `protobuf:"bytes,2,opt,name=merchant_wallet_user_id,json=merchantWalletUserId,proto3" json:"merchant_wallet_user_id,omitempty"`
	Cents                int64                  `protobuf:"varint,3,opt,name=cents,proto3" json:"cents,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_pb_money_movement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_money_movement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_pb_money_movement_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetCustomerWalletUserId() string {
	if x != nil {
		return x.CustomerWalletUserId
	}
	return ""
}

func (x *AuthorizeRequest) GetMerchantWalletUserId() string {
	if x != nil {
		return x.MerchantWalletUserId
	}
	return ""
}

func (x *AuthorizeRequest) GetCents() int64 {
	if x != nil {
		return x.Cents
	}
	return 0
}

func (x *AuthorizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_pb_money_movement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_money_movement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_pb_money_movement_proto_rawDescGZIP(), []int{1}
}

func (x *CaptureRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_pb_money_movement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_money_movement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_pb_money_movement_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

var File_pb_money_movement_proto protoreflect.FileDescriptor

const file_pb_money_movement_proto_rawDesc = "" +
	"\n" +
	"\x17pb/money_movement.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x01\n" +
	"\x10AuthorizeRequest\x125\n" +
	"\x17customer_wallet_user_id\x18\x01 \x01(\tR\x14customerWalletUserId\x125\n" +
	"\x17merchant_wallet_user_id\x18\x02 \x01(\tR\x14merchantWalletUserId\x12\x14\n" +
	"\x05cents\x18\x03 \x01(\x03R\x05cents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\"\n" +
	"\x0eCaptureRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"%\n" +
	"\x11AuthorizeResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid2~\n" +
	"\x14MoneyMovementService\x122\n" +
	"\tAuthorize\x12\x11.AuthorizeRequest\x1a\x12.AuthorizeResponse\x122\n" +
	"\aCapture\x12\x0f.CaptureRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/airlangga-hub/microservices-payment/money_movement/pbb\x06proto3"

var (
	file_pb_money_movement_proto_rawDescOnce sync.Once
	file_pb_money_movement_proto_rawDescData []byte
)

func file_pb_money_movement_proto_rawDescGZIP() []byte {
	file_pb_money_movement_proto_rawDescOnce.Do(func() {
		file_pb_money_movement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_money_movement_proto_rawDesc), len(file_pb_money_movement_proto_rawDesc)))
	})
	return file_pb_money_movement_proto_rawDescData
}

var file_pb_money_movement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_money_movement_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),  // 0: AuthorizeRequest
	(*CaptureRequest)(nil),    // 1: CaptureRequest
	(*AuthorizeResponse)(nil), // 2: AuthorizeResponse
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_pb_money_movement_proto_depIdxs = []int32{
	0, // 0: MoneyMovementService.Authorize:input_type -> AuthorizeRequest
	1, // 1: MoneyMovementService.Capture:input_type -> CaptureRequest
	2, // 2: MoneyMovementService.Authorize:output_type -> AuthorizeResponse
	3, // 3: MoneyMovementService.Capture:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_money_movement_proto_init() }
func file_pb_money_movement_proto_init() {
	if File_pb_money_movement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_money_movement_proto_rawDesc), len(file_pb_money_movement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_money_movement_proto_goTypes,
		DependencyIndexes: file_pb_money_movement_proto_depIdxs,
		MessageInfos:      file_pb_money_movement_proto_msgTypes,
	}.Build()
	File_pb_money_movement_proto = out.File
	file_pb_money_movement_proto_goTypes = nil
	file_pb_money_movement_proto_depIdxs = nil
}
